apiVersion: v1
kind: Service
metadata:
  name: booking-app-deploy
  namespace: namespace-workflow-1699352405666
spec:
  type: LoadBalancer
  selector:
    app: booking-app-deploy
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000